name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-south-1'
        
    - name: Debug CodeArtifact Auth Token
      run: |
        export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain java --domain-owner 669283534479 --duration-seconds 3600 --region ap-south-1 --query authorizationToken --output text)
        echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain java --domain-owner 669283534479 --duration-seconds 3600 --region ap-south-1 --query authorizationToken --output text)" >> $GITHUB_ENV
        echo "CODEARTIFACT_AUTH_TOKEN: $CODEARTIFACT_AUTH_TOKEN"

    - name: Push Artifact to AWS CodeArtifact
      run: |
        mvn --no-transfer-progress -s settings.xml clean package deploy

    - name: Copy JAR to S3
      run: |
        cd target
        ls -lrt
        aws s3 cp *.jar s3://mybucketformyproject/devops-infra

