

name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: List the current working directory
      run: |
        ls -lart
        cd target
        ls -lart
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'
        
    - name: Debug CodeArtifact Auth Token
      run: |
        export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain java --domain-owner 669283534479 --region ap-south-1 --query authorizationToken --output text)
        echo $CODEARTIFACT_AUTH_TOKEN

      
    - name: Push Artifact to AWS CodeArtifact
      run: |
        export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain java --domain-owner 669283534479 --region ap-south-1 --query authorizationToken --output text)
        echo $CODEARTIFACT_AUTH_TOKEN
        mvn clean package deploy -s settings.xml
      
      
